### PR TITLE
academic track's proceedings

### PR DESCRIPTION
**Pull request by tyrasd**
todos:

* [x] get list of talks DOIs (zenodo) from @marcominghini
* [x] get combined overall proceedings PDF and host on website
* [x] add link to DOIs to individual sessions' pages

### CODE REVIEW

**Comment by MarcoMinghini** [comment]
@tyrasd thanks! While the PDFs of single papers are stored on Zenodo, the single PDF of the whole proceedings should be stored somewhere (and linked to the website for download). Any suggestion where this can be stored?

**Comment by tyrasd** [comment]
> Any suggestion where this can be stored?

Ah ok. We can just store it here in this repository. Similar to https://github.com/openstreetmap/stateofthemap-2019/blob/master/Sponsorship2019.pdf

**Comment by Nakaner** [comment]
IMHO, all PDFs should be hosted at 2019.stateofthemap.org. Anything which belongs to the conference except videos should be part of this repository. Experience from more than 20 years of WWW tells us that links will break.

**Comment by tyrasd** [comment]
As far as I know, the DOI system was created to explicitly circumvent these issues one normally has with hyperlinks. see https://en.wikipedia.org/wiki/Digital_object_identifier

**Comment by MarcoMinghini** [comment]
Yes, this is correct. Zenodo is also a research platform that will store not just the pdf, but all the (research) metadata, including the doi (i.e. what we really need).

No problem to also store a copy of each pdf on the website, but the links should point to Zenodo.

**Comment by tyrasd** [comment]
almost ready (there's a preview currently at https://giscience.github.io/stateofthemap-2019/academic_proceedings/). just let me know if you have the completed full PDF ready

**Comment by MarcoMinghini** [comment]
Thanks @tyrasd. Just few comments:

- the text "2019" in "State of the Map 2019" (first line at the top) seems to have a different font. But then I noticed that the font on the 'real' website is different so I guess this is not a problem.

- we agreed internally to publish also the complete PDF on Zenodo (with a DOI), since this will result into a more 'official' and 'recognized' product. I can already give you the DOI link:
http://doi.org/10.5281/zenodo.3405431. You can leave the text as it is, i.e. "... can be downloaded [here](http://doi.org/10.5281/zenodo.3405431.)". 

- we are discussing on whether it is clear that clicking on the links you can access the pdf (in my opinion not so much, but I asked the others) and also whether page numbers can be also added to each abstract citation. I'll be back soon with this.

**Comment by tyrasd** [comment]
>the text "2019" in "State of the Map 2019" (first line at the top) seems to have a different font.

fixed the font

>we agreed internally to publish also the complete PDF on Zenodo (with a DOI), since this will result into a more 'official' and 'recognized' product. I can already give you the DOI link: http://doi.org/10.5281/zenodo.3405431. You can leave the text as it is, i.e. "... can be downloaded here".

done

>we are discussing on whether it is clear that clicking on the links you can access the pdf (in my opinion not so much, but I asked the others) and also whether page numbers can be also added to each abstract citation. I'll be back soon with this.

maybe make the link text indicate that they contain a pdf, e.g.:
`https://doi.org/……/zenodo.…… (pdf)`?

**Comment by MarcoMinghini** [comment]
Hi Martin, we are agreeing on the preferred format to reference the PDF from Zenodo - I should be able to send you everything by today.

**Comment by tyrasd** [comment]
ok!

**Comment by tyrasd** [comment]
any news regarding the overpass proceedings pdf? we could also merge this "as is" and add the full proceedings a bit later to the website…

**Comment by MarcoMinghini** [comment]
@tyrasd I'm working on it now. You will have everything in 1-2 hours!

**Comment by MarcoMinghini** [comment]
Here some updates and last instructions.

All the single abstracts + the full pdf of proceedings are now published in Zenodo. 

**NOTE**: I had an issue with one abstract (the first one, title: "Bridging the Map? Exploring Interactions between the Academic and Mapping Communities in OpenStreetMap") and I had to create a 2nd version of it with a new DOI: 10.5281/zenodo.3408639 so the link to it is now doi.org://10.5281/zenodo.3408639

The page https://giscience.github.io/stateofthemap-2019/academic_proceedings/ is no longer accessible, however we agreed on some minor changes in the web page of proceedings:

- substitute the sentence "Below you find the proceedings of all submissions individually" with "PDF versions of individual abstracts are available under CC BY SA 4.0 from Zenodo."

- as already said, we decided to also publish the single pdf of the proceedings on Zenodo. Thus, the text should be "... can be downloaded [here](http://doi.org/10.5281/zenodo.3405431)".

- we would change the formatting of each single abstract in this way: 

Author1, Author2, ... and AuthorN, Title [session] [full abstract - pdf]

where:
- "session" links to the session page (for example https://2019.stateofthemap.org/sessions/RZXQP3/)
- "full abstract - pdf" links to the Zenodo page (for example https://zenodo.org/record/3408639)
- no need to show the doi (we only show it in Zenodo)
- no need for italic text

It is totally fine if you do that tomorrow (or when you have time). Then, it would be great to tweet that the Academic Track proceedings have been published, with a link to the new website page.

Once again, thank you @tyrasd from all of us!

**Comment by MarcoMinghini** [comment]
Also, it would be nice to add a link to the proceedings page from the Academic programme page, e.g. edit the current text as "The call for abstracts of the academic track which lead to this selection of talks can be found **_here_** and the conference proceedings including all the accepted abstracts can be found **_here_**."

**Comment by tyrasd** [comment]
> Author1, Author2, ... and AuthorN, Title [session] [full abstract - pdf]

I've changed this and updated the preview age. Is it fine like this: https://giscience.github.io/stateofthemap-2019/academic_proceedings/

Is it correct that the links to the abstracts should be directly to the zenodo page (e.g. https://zenodo.org/record/3408639) and not the corresponding doi.org link (e.g. https://doi.org/10.5281/zenodo.3408639) which redirects to the same page on zenodo.org?

> NOTE: I had an issue with one abstract 

fixed :white_check_mark: 

> Also, it would be nice to add a link to the proceedings page from the Academic programme page, e.g. edit the current text as "The call for abstracts of the academic track which lead to this selection of talks can be found **_here_** and the conference proceedings including all the accepted abstracts can be found **_here_**."

The page already had a link to the proceedings from this PR. The text was slightly different though (_“The **call for abstracts** which lead to this selection of talks as well as the track's **proceedings** can be found on this website as well.”_). Is this fine like this?

**Comment by MarcoMinghini** [comment]
> Is it correct that the links to the abstracts should be directly to the zenodo page (e.g. https://zenodo.org/record/3408639) and not the corresponding doi.org link (e.g. https://doi.org/10.5281/zenodo.3408639) which redirects to the same page on zenodo.org?

Practically it is the same thing: if you use the link with the doi, you will be redirected to the same page. Probably it would be better to use the link to the doi since this is a unique identifier (e.g. suppose that in the future they will change the Zenodo way of creating URLs, the link with the doi will still work).

> The page already had a link to the proceedings from this PR. The text was slightly different though (“The call for abstracts which lead to this selection of talks as well as the track's proceedings can be found on this website as well.”). Is this fine like this?

I slightly prefer the new text, but both the versions are fine!

**Comment by MarcoMinghini** [comment]
@tyrasd there's something to fix in the website :)

image

**Comment by tyrasd** [comment]
it's fixed in https://github.com/openstreetmap/stateofthemap-2019/commit/78e8b5eea7a1cbddbb89f9e490da6d3441ca0ed0

**Comment by MarcoMinghini** [comment]
Also, the doi to the first abstract (Bridging the Map? Exploring Interactions between the Academic and Mapping Communities in OpenStreetMap) is the old one (old version). The new one is https://zenodo.org/record/3408639 , can you point to this one?

**Comment by tyrasd** [comment]
oops, sorry for the mistake. It's fixed in https://github.com/openstreetmap/stateofthemap-2019/commit/157ee80092dee5c1fda04133f3693b3176ca706d

**Comment by MarcoMinghini** [comment]
Thanks @tyrasd. We have discussed about the overall appearance of the list of abstracts, and we think this might be improved.
We will directly make a pull request tonight (so no more work for you Martin, but please accept it :) )

**Comment by tyrasd** [comment]
sure, go ahead!

**Comment by MarcoMinghini** [comment]
Here the PR ready to be merged: https://github.com/openstreetmap/stateofthemap-2019/pull/40

**Comment by jlevente** [comment]
Hi @tyrasd . I've used the old title of an abstract in the previous PR. Can you please merge https://github.com/openstreetmap/stateofthemap-2019/pull/41 that fixes this oversight?

**Pull request merged**
